# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               '[ts] not zi-hang'
tagline:             'Stuff I found interesting'
description:         'I study Computer Science in UCLA as a graduate student. This site is built to store and share thoughts on interesting technologies.'
url:                 https://seanxwzhang.github.io
baseurl:             ''

# About/contact
author:
  name:              Sean Xiaowen Zhang
  url:               https://github.com/seanxwzhang
  email:             seanxwzhang@gmail.com

# Custom vars
version:             1.0.1

# Gems
gems:				         [jekyll-paginate]
paginate: 		       1
# paginate_path: 		"~/Dropbox/Personal Website/seanxwzhang.github.io/page:num"

markdown:            kramdown
