project:
  type: website
  output-dir: docs

website:
  title: "Ramblings on Deep Learning"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/seanxwzhang
      - icon: twitter
        href: https://x.com/seeeeaaaannnnnn
      - icon: linkedin
        href: https://www.linkedin.com/in/seanxwz/
      - icon: rss
        href: index.xml
  site-url: https://seanzhang.me
  description: "Ramblings on Deep Learning"
format:
  html:
    theme:
      - sandstone
    css: styles.css



